name: emmaenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - plotly
  - colorama
  - dash
  - dash-bootstrap-components
  - dash-core-components
  - dash-daq
  - miranda
  - bedtools
  - pip
  - openpyxl
  - pip:
      - kaleido